doctrine_migrations:
    dir_name: '%kernel.project_dir%/migrations'
    namespace: DoctrineMigration
    table_name: migration_versions
    name: 'Application Migrations'
    organize_migrations: BY_YEAR_AND_MONTH
